fixes issues with xml parser not working
scientist-softserv/britishlibrary pull request #237
Opened 2023-01-07 05:11 UTC by sephirothkod

parsed_metadata global/local correction. updated the create_objects method to call other create methods as it is unsupported for xml parsers.

2023-01-09 18:50 UTC, alishaevn requested changes

2023-01-09 18:50 UTC, alishaevn commented on app/ parsers/bulkrax/xml_etd_dc_parser.rb
> +      end
shouldn't the action in these two conditionals be reversed?

2023-01-10 21:19 UTC, jeremyf commented on app/ parsers/bulkrax/xml_etd_dc_parser.rb
> +    def create_objects(type_array)
What about file_sets?  In the `create_filesets` method we call `create_objects['file_set']` which wouldn't be handled.

2023-01-10 21:19 UTC, jeremyf requested changes
Need to resolve the `create_filesets` method

2023-01-18 00:13 UTC, jeremyf approved these changes

2023-01-18 16:10 UTC, alishaevn approved these changes

2023-01-18 16:47 UTC, merged